import type { ConceptNode } from '../types'
import type { BackendNode, GraphContext } from '../types/api'
import type { MindMapState } from '../types'

export class NodeAdapter {
  static fromBackend(backendNode: any): ConceptNode {
    return {
      id: backendNode.id,
      label: backendNode.label,
      concept: backendNode.concept,
      isExplored: backendNode.isExplored,
      preferenceScore: backendNode.preferenceScore,
      position: backendNode.position,
      parentId: backendNode.parentId || undefined,
      children: backendNode.children || [],
      createdAt: new Date(backendNode.createdAt),
      contentType: backendNode.contentType || 'text', // Default to text for backward compatibility
      contentUrl: backendNode.contentUrl || undefined,
      metadata: {
        keywords: backendNode.metadata?.keywords || [],
        summary: backendNode.metadata?.summary || `${backendNode.concept} - Generated by AI`,
        sources: backendNode.metadata?.sources || []
      }
    }
  }

  static toBackend(frontendNode: ConceptNode): BackendNode {
    return {
      id: frontendNode.id,
      concept: frontendNode.concept,
      label: frontendNode.label,
      isExplored: frontendNode.isExplored,
      preferenceScore: frontendNode.preferenceScore,
      position: frontendNode.position,
      children: frontendNode.children,
      createdAt: frontendNode.createdAt.toISOString()
    }
  }

  static buildContext(state: MindMapState): GraphContext {
    return {
      centerConcept: state.centerConcept,
      isGenerating: state.isGenerating,
      nodes: state.nodes.map(node => ({
        id: node.id,
        concept: node.concept,
        label: node.label,
        isExplored: node.isExplored,
        preferenceScore: node.preferenceScore,
        position: node.position,
        children: node.children
      }))
    }
  }

  static fromInitResponse(response: { centerNode: any; nodes: any[] }): {
    centerNode: ConceptNode
    nodes: ConceptNode[]
  } {
    const centerNode = this.fromBackend(response.centerNode)
    
    const initialNodes = response.nodes.map(node => this.fromBackend(node))

    // Apply canvas positioning to all nodes
    const allNodes = [centerNode, ...initialNodes]
    const positionedNodes = this.calculateCanvasPositions(allNodes)

    return {
      centerNode: positionedNodes.find(n => n.id === centerNode.id) || centerNode,
      nodes: positionedNodes
    }
  }

  static fromExpandResponse(response: {
    parent_updated: any
    children: any[]
    reward: number
  }): {
    parentUpdated: ConceptNode
    children: ConceptNode[]
    reward: number
  } {
    const parentUpdated = this.fromBackend(response.parent_updated)
    const children = response.children.map(child => this.fromBackend(child))

    return {
      parentUpdated,
      children,
      reward: response.reward
    }
  }

  static fromPreferenceResponse(response: {
    updated_node: any
    affected_siblings: any[]
  }): {
    updatedNode: ConceptNode
    affectedSiblings: ConceptNode[]
  } {
    return {
      updatedNode: this.fromBackend(response.updated_node),
      affectedSiblings: response.affected_siblings.map(sibling => 
        this.fromBackend(sibling)
      )
    }
  }

  static calculateCanvasPositions(
    nodes: ConceptNode[],
    centerPosition: { x: number; y: number } = { x: 600, y: 400 }
  ): ConceptNode[] {
    return nodes.map(node => {
      if (node.id.includes('center')) {
        return { ...node, position: centerPosition }
      }

      // For initial radial nodes, calculate positions around center
      if (node.parentId && node.parentId.includes('center')) {
        const siblingIndex = nodes
          .filter(n => n.parentId === node.parentId)
          .findIndex(n => n.id === node.id)
        
        const angle = (siblingIndex * 2 * Math.PI) / 4 // Assume 4 initial nodes
        const radius = 200
        
        return {
          ...node,
          position: {
            x: centerPosition.x + Math.cos(angle) * radius,
            y: centerPosition.y + Math.sin(angle) * radius
          }
        }
      }

      // For child nodes, use backend position or calculate around parent
      const parent = nodes.find(n => n.id === node.parentId)
      if (parent) {
        const siblings = nodes.filter(n => n.parentId === node.parentId)
        const siblingIndex = siblings.findIndex(n => n.id === node.id)
        const totalSiblings = siblings.length

        const angle = (siblingIndex * 2 * Math.PI) / totalSiblings
        const radius = 150
        
        return {
          ...node,
          position: {
            x: parent.position.x + Math.cos(angle) * radius,
            y: parent.position.y + Math.sin(angle) * radius
          }
        }
      }

      // Fallback to backend position
      return node
    })
  }
}