import type { ConceptNode } from '../types'
import type { BackendNode, GraphContext } from '../types/api'
import type { MindMapState } from '../types'
import { CURRENT_LAYOUT, type LayoutOption } from '../config/layoutConfig'

export class NodeAdapter {
  // Configuration for layout testing - easy to switch between options
  private static LAYOUT_OPTION: LayoutOption = CURRENT_LAYOUT
  static fromBackend(backendNode: any): ConceptNode {
    // Debug: Log what we're receiving from backend
    console.log('🔍 NodeAdapter.fromBackend - Raw backend node:', {
      id: backendNode.id,
      concept: backendNode.concept,
      hasMetadata: !!backendNode.metadata,
      metadata: backendNode.metadata,
      metadataKeys: backendNode.metadata ? Object.keys(backendNode.metadata) : []
    })

    // Preserve entire metadata object if it exists, ensuring required fields have defaults
    const metadata = backendNode.metadata ? {
      ...backendNode.metadata,
      keywords: backendNode.metadata.keywords || [],
      summary: backendNode.metadata.summary || `${backendNode.concept} - Generated by AI`,
      sources: backendNode.metadata.sources || [],
      uncertainty_score: backendNode.metadata.uncertainty_score
    } : {
      keywords: [],
      summary: `${backendNode.concept} - Generated by AI`,
      sources: [],
      uncertainty_score: undefined
    }

    console.log('✅ NodeAdapter.fromBackend - Processed metadata:', {
      hasKeywords: !!metadata.keywords && metadata.keywords.length > 0,
      hasSources: !!metadata.sources && metadata.sources.length > 0,
      hasSummary: !!metadata.summary,
      hasUncertaintyScore: metadata.uncertainty_score !== undefined,
      metadata
    })

    return {
      id: backendNode.id,
      label: backendNode.label,
      concept: backendNode.concept,
      isExplored: backendNode.isExplored,
      preferenceScore: backendNode.preferenceScore,
      position: backendNode.position,
      parentId: backendNode.parentId || undefined,
      children: backendNode.children || [],
      createdAt: new Date(backendNode.createdAt),
      contentType: backendNode.contentType || 'text', // Default to text for backward compatibility
      contentUrl: backendNode.contentUrl || undefined,
      metadata
    }
  }

  static toBackend(frontendNode: ConceptNode): BackendNode {
    return {
      id: frontendNode.id,
      concept: frontendNode.concept,
      label: frontendNode.label,
      isExplored: frontendNode.isExplored,
      preferenceScore: frontendNode.preferenceScore,
      position: frontendNode.position,
      children: frontendNode.children,
      createdAt: frontendNode.createdAt.toISOString()
    }
  }

  static buildContext(state: MindMapState): GraphContext {
    return {
      centerConcept: state.centerConcept,
      isGenerating: state.isGenerating,
      nodes: state.nodes.map(node => ({
        id: node.id,
        concept: node.concept,
        label: node.label,
        isExplored: node.isExplored,
        preferenceScore: node.preferenceScore,
        position: node.position,
        children: node.children
      }))
    }
  }

  static fromInitResponse(response: { centerNode: any; nodes: any[] }): {
    centerNode: ConceptNode
    nodes: ConceptNode[]
  } {
    const centerNode = this.fromBackend(response.centerNode)
    
    const initialNodes = response.nodes.map(node => this.fromBackend(node))

    // Apply canvas positioning to all nodes
    const allNodes = [centerNode, ...initialNodes]
    const positionedNodes = this.calculateCanvasPositions(allNodes, { x: 600, y: 400 }, this.LAYOUT_OPTION)

    return {
      centerNode: positionedNodes.find(n => n.id === centerNode.id) || centerNode,
      nodes: positionedNodes
    }
  }

  static fromExpandResponse(response: {
    parent_updated: any
    children: any[]
    reward: number
  }): {
    parentUpdated: ConceptNode
    children: ConceptNode[]
    reward: number
  } {
    const parentUpdated = this.fromBackend(response.parent_updated)
    const children = response.children.map(child => this.fromBackend(child))

    return {
      parentUpdated,
      children,
      reward: response.reward
    }
  }

  static fromPreferenceResponse(response: {
    updated_node: any
    affected_siblings: any[]
  }): {
    updatedNode: ConceptNode
    affectedSiblings: ConceptNode[]
  } {
    return {
      updatedNode: this.fromBackend(response.updated_node),
      affectedSiblings: response.affected_siblings.map(sibling => 
        this.fromBackend(sibling)
      )
    }
  }

  // Layout Options for Initial Nodes
  private static getLayoutOption1_Compass(siblingIndex: number): { angle: number; radius: number } {
    const compassAngles = [-Math.PI / 2, 0, Math.PI / 2, Math.PI] // Top, Right, Bottom, Left
    return { angle: compassAngles[siblingIndex % 4], radius: 300 }
  }

  private static getLayoutOption2_Diamond(siblingIndex: number): { angle: number; radius: number } {
    const diamondAngles = [-Math.PI / 4, Math.PI / 4, 3 * Math.PI / 4, -3 * Math.PI / 4] // NE, SE, SW, NW
    return { angle: diamondAngles[siblingIndex % 4], radius: 280 }
  }

  private static getLayoutOption3_Asymmetric(siblingIndex: number): { angle: number; radius: number } {
    const asymmetricAngles = [(-Math.PI / 2) + 0.26, 0 + 0.26, (Math.PI / 2) + 0.26, Math.PI + 0.26] // 15° offset from cardinal
    return { angle: asymmetricAngles[siblingIndex % 4], radius: 320 }
  }

  private static getLayoutOption4_Progressive(siblingIndex: number, conceptLength: number): { angle: number; radius: number } {
    const compassAngles = [-Math.PI / 2, 0, Math.PI / 2, Math.PI]
    const baseRadius = 280
    const radiusAdjustment = Math.min(60, conceptLength * 1.5) // Longer names get more space
    return { angle: compassAngles[siblingIndex % 4], radius: baseRadius + radiusAdjustment }
  }

  static calculateCanvasPositions(
    nodes: ConceptNode[],
    centerPosition: { x: number; y: number } = { x: 600, y: 400 },
    layoutOption: 'compass' | 'diamond' | 'asymmetric' | 'progressive' = 'compass'
  ): ConceptNode[] {
    return nodes.map(node => {
      if (node.id.includes('center')) {
        return { ...node, position: centerPosition }
      }

      // For initial radial nodes, calculate positions around center
      if (node.parentId && node.parentId.includes('center')) {
        const siblingIndex = nodes
          .filter(n => n.parentId === node.parentId)
          .findIndex(n => n.id === node.id)
        
        // Get layout configuration based on selected option
        let layout: { angle: number; radius: number }
        
        switch (layoutOption) {
          case 'compass':
            layout = this.getLayoutOption1_Compass(siblingIndex)
            break
          case 'diamond':
            layout = this.getLayoutOption2_Diamond(siblingIndex)
            break
          case 'asymmetric':
            layout = this.getLayoutOption3_Asymmetric(siblingIndex)
            break
          case 'progressive':
            layout = this.getLayoutOption4_Progressive(siblingIndex, node.concept.length)
            break
          default:
            layout = this.getLayoutOption1_Compass(siblingIndex)
        }
        
        return {
          ...node,
          position: {
            x: centerPosition.x + Math.cos(layout.angle) * layout.radius,
            y: centerPosition.y + Math.sin(layout.angle) * layout.radius
          }
        }
      }

      // For child nodes, use backend position or calculate around parent
      const parent = nodes.find(n => n.id === node.parentId)
      if (parent) {
        const siblings = nodes.filter(n => n.parentId === node.parentId)
        const siblingIndex = siblings.findIndex(n => n.id === node.id)
        const totalSiblings = siblings.length

        const angle = (siblingIndex * 2 * Math.PI) / totalSiblings
        const radius = 150
        
        return {
          ...node,
          position: {
            x: parent.position.x + Math.cos(angle) * radius,
            y: parent.position.y + Math.sin(angle) * radius
          }
        }
      }

      // Fallback to backend position
      return node
    })
  }
}